# Compose files for fabric-snackbar service

# Tips:
# For variables like '${FABRIC_VERSION}', see '.env' file for definition

version: '2'


services:
  ccenv:
    image: hyperledger/fabric-ccenv:${FABRIC_VERSION}
    container_name: ccenv

  zookeeper:
    image: hyperledger/fabric-zookeeper:${FABRIC_VERSION}
    container_name: zookeeper

  kafka:
    image: hyperledger/fabric-kafka:${FABRIC_VERSION}
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_MESSAGE_MAX_BYTES: 103809024
      KAFKA_REPLICA_FETCH_MAX_BYTES: 103809024
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  ## Dynamic Scalable Components

  ## Orderer

  orderer.ibm.com:
    extends:
      file: ./components/orderer.yml
      service: orderer
    container_name: orderer.ibm.com
    hostname: orderer.ibm.com
    environment:
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer-msp
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./channel/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/ibm.com/orderers/orderer.ibm.com/msp/:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/ibm.com/orderers/orderer.ibm.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - "7050:7050"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer



  ## CA
  ca.little-factory.com:
    extends:
      file: ./components/ca.yml
      service: ca
    container_name: ca.little-factory.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "7054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/little-factory.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: >
      sh -c 'fabric-ca-server start
      --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.little-factory.com-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6b17bdc5920c78d0a46a59145671e68aee3662569e6862048edf16eb6d885f87_sk
      -b admin:adminpw' -d

  ca.little-snackbar.com:
    extends:
      file: ./components/ca.yml
      service: ca
    container_name: ca.little-snackbar.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "8054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/little-snackbar.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: >
      sh -c 'fabric-ca-server start
      --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.little-snackbar.com-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/032c54edf6bec1f8ac538748f82b5516ea1da16206a9ba1b288baa2b672e5e15_sk
      -b admin:adminpw' -d

  ## Peer
  peer0.little-factory.com:
    extends:
      file: ./components/peer.yml
      service: peer
    container_name: peer0.little-factory.com
    hostname: peer0.little-factory.com
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/little-factory.com/peers/peer0.little-factory.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/little-factory.com/peers/peer0.little-factory.com/tls:/etc/hyperledger/fabric/tls
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_default
      - CORE_PEER_LOCALMSPID=factory-msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.little-factory.com
      - CORE_PEER_ADDRESS=peer0.little-factory.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.little-factory.com:7051
    ports:
      - "7051:7051"
      - "7053:7053"
    command: peer node start --peer-defaultchain=false
    depends_on:
      - orderer.ibm.com


  peer1.little-factory.com:
    extends:
      file: ./components/peer.yml
      service: peer
    container_name: peer1.little-factory.com
    hostname: peer1.little-factory.com
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/little-factory.com/peers/peer1.little-factory.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/little-factory.com/peers/peer1.little-factory.com/tls:/etc/hyperledger/fabric/tls
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_default
      - CORE_PEER_LOCALMSPID=factory-msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.little-factory.com
      - CORE_PEER_ADDRESS=peer1.little-factory.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.little-factory.com:7051
    ports:
      - "7056:7051"
      - "7058:7053"
    command: peer node start --peer-defaultchain=false
    depends_on:
      - orderer.ibm.com
      - peer0.little-factory.com

  peer0.little-snackbar.com:
    extends:
      file: ./components/peer.yml
      service: peer
    container_name: peer0.little-snackbar.com
    hostname: peer0.little-snackbar.com
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/little-snackbar.com/peers/peer0.little-snackbar.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/little-snackbar.com/peers/peer0.little-snackbar.com/tls:/etc/hyperledger/fabric/tls
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_default
      - CORE_PEER_LOCALMSPID=snackbar-msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.little-snackbar.com
      - CORE_PEER_ADDRESS=peer0.little-snackbar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.little-snackbar.com:7051
    ports:
      - "8051:7051"
      - "8053:7053"
    command: peer node start --peer-defaultchain=false
    depends_on:
      - orderer.ibm.com

  peer1.little-snackbar.com:
    extends:
      file: ./components/peer.yml
      service: peer
    container_name: peer1.little-snackbar.com
    hostname: peer1.little-snackbar.com
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/little-snackbar.com/peers/peer1.little-snackbar.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/little-snackbar.com/peers/peer1.little-snackbar.com/tls:/etc/hyperledger/fabric/tls
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=artifacts_default
      - CORE_PEER_LOCALMSPID=factory-msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp/
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.little-snackbar.com
      - CORE_PEER_ADDRESS=peer1.little-snackbar.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.little-snackbar.com:7051
    ports:
      - "8056:7051"
      - "8058:7053"
    command: peer node start --peer-defaultchain=false
    depends_on:
      - orderer.ibm.com
      - peer0.little-snackbar.com
